fc_cross_validation:
  input:
    data: "data.csv"
    label_column: 10
    sep: ","
  output:
    train: "train.csv"
    test: "test.csv"
    split_dir: "data"
  cross_validation:
    n_splits: 3
    stratify: false
    random_state: 42
    n_repeats: 3