fc_cross_validation:
  input:
    data: "data.npy" # or data.csv File containing the actual data
    label_column: "target" # Name of the column including the labels. Can be None if stratify is false
    sep: "," # Separator of the data file.
  output:
    train: "train.csv" # Output filename of the train set
    test: "test.csv" # Output filename of the test set
    split_dir: "data" # name of the dir including the splits
  cross_validation:
    n_splits: 10 # number of splits
    shuffle: true # Data will be shuffled before splits are created
    stratify: false # If true, labels will be equally distributed between the splits. If true, label_column cannot be Null
    random_state: Null # Seed to create reproducible splits, Null possible